### PR TITLE
feat: new front page catalog

### PR DESCRIPTION
**Pull request by arzola**
This PR address #365 

How to test:

1. Navigate to the customizer and enable the front end catalog
2. Select your 4 books of the catalog you should preview after selecting each of them
3. Review if your selection is previewed in the book customizer
4. Try to use the same book in two selects (it should not be possible)
5. Enjoy your new simplified front page
6. The old catalog should be working as before

image

### CODE REVIEW

**Review by SteelWagstaff — COMMENTED** [review]
If we totally remove support for the old catalog, then I think we would need to 'require' pressbooks-network-catalog as a dependency. Otherwise open source users who try to use this new feature but don't have the new catalog will see something like this on their catalog page: 
Screenshot from 2022-11-03 16-55-00
instead of the expected 'old' catalog:
Screenshot from 2022-11-03 16-55-55

**Comment by arzola** [comment]
I sent a change to revert the catalog scripts removal and the old catalog should still work

**Review by fdalcin — CHANGES_REQUESTED** [review]
Changes look good to me and feature work as expected. 

However, before selecting the featured books for the first time (when all of them were empty) the page displayed everything in the "Featured Books" section.

image

**Comment by arzola** [comment]
@fdalcin thanks for the observation I sent a fix for that

**Review by fdalcin — APPROVED** [review]

**Comment by fdalcin** [comment]
LGTM, thank you @arzola

**Pull request merged**
